### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by viza123** [dneg/nagios#6]
We are using check_pa_config_sync.pl for palo alto out of sync monitoring.
so we have issues with this plugin, It is always giving the same output as 
CRITICAL - No results returned from palo altos. Is the host dead? Wrong API key.
We tested the token with other plugin and it works fine for that plugin.

I'm not sure why this plugin is not supporting .
And does this plugin support PA5220 and also do we have any similar plugins to monitor it?

Looking forward to hear from you soon.

**Comment by adambarnett52** [comment]
Hi, 

This was written a while ago for a PA=5060 and were running an old build of PanOS
We no longer have these so i am unable to test on a newer version of PanOS

At a guess i would suspect that you output that is being matched has changed 

All the best 
Adam
